### PR TITLE
fix supplemental bug and add sanity test

### LINKED ISSUE #21: postalCodeData is no longer present in unicode-cldr 28.0
`postalCodeData` is no longer present here:
https://github.com/unicode-cldr/cldr-core/tree/28.0.0/supplemental

Because of this, `index.js` fails to run since, it tries to require this file:
https://github.com/rxaviers/cldr-data-npm/blob/master/index.js#L23

### PR DESCRIPTION
**Pull request by alunny**
Fixes #21

### CODE REVIEW

**Comment by rxaviers** [comment]
That was quick! Thanks.

Do you think it makes sense to do the same for the main files?

**Comment by alunny** [comment]
Yeah, that makes sense.

**Comment by rxaviers** [comment]
Landed. Released as `28.0.1`. Thanks

**Comment by rxaviers** [comment]
PS: Landed on all previous branches as well. 27.x, 26.x, ...

**Comment by rxaviers** [comment]
Amended by the commit listed above ^.

**Comment by alunny** [comment]
Actually there's a bug that prevents this working as a dependency - `fs.readdirSync` reads relative to `pwd`, not to `__dirname`. So the script fails when it's called from a top level with `cldr-data` under `node_modules`.

Sorry about that - patch forthcoming.

**Comment by rxaviers** [comment]
I've already fixed it. :)

**Comment by alunny** [comment]
Nice, thanks :)

**Comment by rxaviers** [comment]
Are you talking about https://github.com/rxaviers/cldr-data-npm/commit/4303ce1444642e26f4ad5e95f778a74f341d7b42 or a fix on top of that?

**Comment by alunny** [comment]
I think that's right, trying 28.0.2 now.

**Comment by rxaviers** [comment]
;)

**Pull request closed without merging**
